# Use distribution Ubuntu 18.04 Bionic
dist: bionic

# Handle dependencies in separate directory.
before_install:
    - DEPS_DIR="${HOME}/deps"
    - mkdir -p "${DEPS_DIR}"
    - cd "${DEPS_DIR}"

# Install necessary packages.
install:
    # Install a recent version of CMake
    - |
        CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
        if [ ! -f ${DEPS_DIR}/cmake/bin/cmake ] ; then mkdir -p cmake ; travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake ; fi
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    # Install a recent version of the Protobuf
    - |
        PROTOBUF_URL="https://github.com/google/protobuf/releases/download/v3.2.0/protobuf-cpp-3.2.0.tar.gz"
        if [ ! -f ${DEPS_DIR}/protobuf/install/bin/protoc ] ; then mkdir -p protobuf ; travis_retry wget --no-check-certificate --quiet -O - ${PROTOBUF_URL} | tar --strip-components=1 -xz -C protobuf ; cd protobuf ; ./configure --prefix=${DEPS_DIR}/protobuf/install ; make ; make install ; fi
        export PATH=${DEPS_DIR}/protobuf/install/bin:${PATH}

    # Install proto2cpp for doxygen
    - |
        PROTO2CPP_URL="https://github.com/OpenSimulationInterface/proto2cpp.git"
        if [ ! -f ${DEPS_DIR}/proto2cpp ] ; then mkdir -p proto2cpp ; git clone ${PROTO2CPP_URL} ${DEPS_DIR}/proto2cpp ; fi
        
    - sudo apt-get install python3-pip
    - sudo pip3 install sphinx_rtd_theme
    - sudo pip3 install sphinx_git
    - sudo apt-get install protobuf-compiler

# Environment variables.
env:
  global:
    - GH_REPO_ORG=`echo $TRAVIS_REPO_SLUG | cut -d "/" -f 1`
    - GH_REPO_NAME=`echo $TRAVIS_REPO_SLUG | cut -d "/" -f 2`
    - GH_REPO_REF="github.com/$GH_REPO_ORG/$GH_REPO_NAME.git"

# Addons necessary for documentation.
addons:
    apt:
        packages:
            - python3-sphinx

# Change directory back to default build directory.
before_script:
    - cd "${TRAVIS_BUILD_DIR}"

# Run the build script and generate documentation.
script:
    # - git clone https://github.com/OpenSimulationInterface/osi-validation.git
    # - cd osi-validation
    # - git checkout development
    # - git clone https://github.com/OpenSimulationInterface/open-simulation-interface.git
    # - git clone https://github.com/OpenSimulationInterface/proto2cpp.git
    # - sudo python3 setup.py install
    # - cd ..
    - make html

# Deploy the documentation on github (only for master branch).
deploy:
    provider: pages
    skip_cleanup: true
    local_dir: doc/html
    keep-history: true
    github_token: ${GH_REPO_TOKEN}
    on: 
      branch: master 